version: 0.1
proxy:
  remoteurl: https://registry-1.docker.io  # 代理到 Docker Hub
storage:
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: true  # 允许清理旧镜像
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
